export const CLI_USAGE_LINES = Object.freeze([
  'chrome-bridge server [--port 17376]',
  'chrome-bridge health',
  'chrome-bridge windows [--all --confirm] [--group-title <title>] [--group-color <color>]',
  'chrome-bridge group [--tabs] [--group-title <title>] [--group-color <color>]',
  'chrome-bridge tabs [--json --summary-only] [--all --confirm] [--group-title <title>] [--group-color <color>]',
  'chrome-bridge workspace [--tabs]',
  'chrome-bridge set-workspace [--name <name>] [--group-title <title>] [--group-color <color>] [--policy-mode scoped|strict] --confirm',
  'chrome-bridge clear-workspace --confirm',
  'chrome-bridge ensure-tab [url] [--active] [--group-title <title>] [--group-color <color>]',
  'chrome-bridge adopt-tab [--tab <id>] [--group-title <title>] [--group-color <color>] --confirm',
  'chrome-bridge open <url> [--tab <id>] [--active] [--new] [--allow-external] [--group-title <title>] [--group-color <color>]',
  'chrome-bridge activate [--tab <id>] [--focus-window] [--allow-external]',
  'chrome-bridge close-tab [--tab <id>] --confirm [--allow-external]',
  'chrome-bridge close-group [--group-title <title>] [--group-color <color>] --confirm',
  'chrome-bridge back [--tab <id>] [--allow-external]',
  'chrome-bridge forward [--tab <id>] [--allow-external]',
  'chrome-bridge reload [--tab <id>] [--bypass-cache] [--allow-external]',
  'chrome-bridge wait (--selector <css> | --ref <ref>) [--timeout-ms 10000] [--hidden-ok] [--tab <id>] [--allow-external]',
  'chrome-bridge observe [--tab <id>] [--limit 80] [--max-text-chars 160] [--allow-external]',
  'chrome-bridge act-preview --intent <text> [--tab <id>] [--max-candidates 5] [--risk read-only|confirmed-interaction|private-read] [--selector-preference stable|any] [--allow-external]',
  'chrome-bridge act-apply --preview-id <id> --confirm [--text <text>] [--value <value> | --label <label> | --index <n>]',
  'chrome-bridge find-elements [--role <role>] [--text <text>] [--near-text <text>] [--placeholder <text>] [--href <text>] [--action <kind>] [--risk <risk>] [--limit 80] [--tab <id>] [--allow-external]',
  'chrome-bridge extract [--kind all|tables|forms|lists|keyValues] [--preset cpa-offer|article|product-page|pricing-table --network <name> --out <file> [--artifact-dir <dir>]] [--max-items 50] [--tab <id>] [--allow-external]',
  'chrome-bridge snapshot [--tab <id>] [--max-chars 200000] [--full-page] [--wait-for-text <text>] [--wait-for-pattern <regex>] [--scroll-step-px <n>] [--max-scroll-steps <n>] [--scroll-delay-ms <n>] [--out <path>] [--summary-only] [--include-content] [--no-content] [--max-inline-chars 4000] [--allow-external]',
  'chrome-bridge text [--tab <id>] [--max-chars 200000] [--full-page] [--wait-for-text <text>] [--wait-for-pattern <regex>] [--scroll-step-px <n>] [--max-scroll-steps <n>] [--scroll-delay-ms <n>] [--out <path>] [--summary-only] [--include-content] [--no-content] [--max-inline-chars 4000] [--allow-external]',
  'chrome-bridge html [--tab <id>] [--selector <css> | --ref <ref>] [--max-chars 500000] [--out <path>] [--inner] [--summary-only] [--include-content] [--no-content] [--max-inline-chars 4000] [--allow-external]',
  'chrome-bridge grep-page --pattern <regex> [--tab <id>] [--artifact-dir <dir>] [--max-matches 20] [--viewport-only] [--allow-external]',
  'chrome-bridge page-search --query <text> [--tab <id>] [--artifact-dir <dir>] [--out <file>] [--max-matches 8] [--max-snippet-chars 320] [--viewport-only] [--allow-external]',
  'chrome-bridge links [--selector <css>] [--tab <id>] [--artifact-dir <dir>] [--allow-external]',
  'chrome-bridge tables [--selector <css>] [--tab <id>] [--artifact-dir <dir>] [--allow-external]',
  'chrome-bridge download-discovery --out <file> [--selector <css>] [--tab <id>] [--artifact-dir <dir>] [--allow-external]',
  'chrome-bridge download (--selector <css> | --ref <ref>) --confirm [--download-timeout-ms <ms>] [--tab <id>] [--allow-external]',
  'chrome-bridge screenshot [--tab <id>] --out <file> [--full-page] [--selector <css> | --ref <ref>] [--max-pixels <n>] [--fallback viewport|error] [--timeout-ms <n>] [--allow-external]',
  'chrome-bridge pdf [--tab <id>] --out <file> [--landscape] [--omit-background] [--page-ranges <ranges>] [--scale <0.1-2>] [--allow-external]',
  'chrome-bridge scroll --tab <id> --y <pixels> [--allow-external]',
  'chrome-bridge set-viewport --width <px> --height <px> --confirm [--device-scale-factor <n>] [--mobile] [--tab <id>] [--allow-external]',
  'chrome-bridge emulate-network --profile offline|slow-3g|fast-3g|slow-4g|wifi|no-throttling|custom --confirm [--latency-ms <n>] [--download-kbps <n>] [--upload-kbps <n>] [--tab <id>] [--allow-external]',
  'chrome-bridge clear-emulation --confirm [--tab <id>] [--allow-external]',
  'chrome-bridge click --tab <id> (--selector <css> | --ref <ref>) --confirm [--allow-external]',
  'chrome-bridge click-at --x <px> --y <px> --confirm [--trusted] [--tab <id>] [--allow-external]',
  'chrome-bridge hover [--selector <css> | --ref <ref>] [--x <px> --y <px>] [--trusted] [--tab <id>] [--allow-external]',
  'chrome-bridge drag-drop (--selector <css> | --ref <ref> | --x <px> --y <px>) (--target-selector <css> | --target-ref <ref> | --target-x <px> --target-y <px>) --confirm [--trusted] [--tab <id>] [--allow-external]',
  'chrome-bridge type --tab <id> (--selector <css> | --ref <ref>) --text <text> --confirm [--trusted] [--allow-external]',
  'chrome-bridge press --key <key> --confirm [--selector <css> | --ref <ref>] [--trusted] [--tab <id>] [--allow-external]',
  'chrome-bridge select (--selector <css> | --ref <ref>) --confirm [--value <value> | --label <label> | --index <n>] [--tab <id>] [--allow-external]',
  'chrome-bridge select-options (--selector <css> | --ref <ref>) [--tab <id>] [--allow-external]',
  'chrome-bridge fill-form --fields-json <json> [--dry-run] [--confirm] [--tab <id>] [--allow-external]',
  'chrome-bridge handle-dialog --confirm [--dismiss] [--prompt-text <text>] [--tab <id>] [--allow-external]',
  'chrome-bridge upload-file (--selector <css> | --ref <ref>) (--file <path> | --files-json <json>) --confirm [--tab <id>] [--allow-external]',
  'chrome-bridge trace-start --confirm [--tab <id>] [--max-events 500] [--no-network] [--no-console] [--include-extension-events] [--allow-external]',
  'chrome-bridge trace-summary [--tab <id>] [--allow-external]',
  'chrome-bridge trace-events [--tab <id>] [--limit 100] [--allow-external]',
  'chrome-bridge diagnostics [--tab <id>] [--out <file>] [--allow-external]',
  'chrome-bridge network-export [--tab <id>] [--artifact-dir <dir>] [--out <file>] [--requests-out <file>] [--har-out <file>] [--limit <n>] [--include-headers --confirm-sensitive] [--include-bodies --confirm-sensitive] [--allow-external]',
  'chrome-bridge lighthouse-plan --url <http(s)://...> [--out <file>] [--summary-out <file>] [--chrome-path <file>] [--chrome-flags <text>] [--emulated-form-factor desktop|mobile] [--only-categories <csv>]',
  'chrome-bridge lighthouse-ingest --report <file> [--out <file>] [--max-audits 25]',
  'chrome-bridge trace-stop [--tab <id>] [--limit 100] [--allow-external]',
  'chrome-bridge history [--query <text>] --confirm [--limit 25] [--start-time <ms>] [--end-time <ms>]',
  'chrome-bridge bookmarks [--query <text>] --confirm [--limit 50]',
  'chrome-bridge cookies [--url <url> | --domain <domain>] --confirm [--include-values --confirm-sensitive] [--limit 50]',
  'chrome-bridge storage [--tab <id>] --confirm [--include-values --confirm-sensitive] [--allow-external]',
  'chrome-bridge request <url> --confirm [--method GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS] [--headers-json <json>] [--body <text>] [--credentials include --confirm-sensitive] [--max-chars 20000] [--request-timeout-ms 60000]',
  'chrome-bridge ask --question <text> [--choices-json <json>] [--no-text] [--timeout-ms 300000] [--keep-tab]',
  'chrome-bridge session-summary',
  'chrome-bridge recording-summary --recording <file> [--limit 500] [--out <file>]',
  'chrome-bridge debug-bundle --out <dir> [--tab <id>] [--allow-external] [--include-snapshot] [--include-observe] [--include-screenshot] [--include-trace-events]',
  'chrome-bridge with-temp-tab <url> [--run-id <id>] [--active] [--keep-tab] [--group-title <title>] [--group-color <color>] -- <text|snapshot|html|screenshot> [read flags]',
  'chrome-bridge cleanup-run-tabs --run-id <id>',
  'chrome-bridge status [--token-budget]',
  'chrome-bridge last-artifact [--artifact-dir <dir>]',
  'chrome-bridge read-artifact --path <file> [--head <n>] [--grep <regex>] [--max-matches <n>]',
  'chrome-bridge command-catalog [--markdown]',
  'chrome-bridge advise --task <text> [--surface cli|mcp|both] [--risk read-only|confirmed-interaction|private-read] [--client claude-code|cursor|codex|vscode|windsurf|hermes|generic] [--live-bridge|--offline]',
  'chrome-bridge mcp-config [--client all|claude-code|cursor|codex|vscode|windsurf|hermes|generic]',
  'chrome-bridge mcp-write --client claude-code|cursor|codex|vscode|windsurf|hermes|generic [--root <dir>] [--out <file>] [--force]',
  'chrome-bridge reload-extension --confirm',
  'chrome-bridge self-test',
  'chrome-bridge runtime-smoke [--keep-tab] [--coverage-plan] [--summary-only] [--out <file>]',
  'chrome-bridge doctor [--live-checks] [--copy-path] [--open-extensions]',
  'chrome-bridge extension-path',
  'chrome-bridge codex-config',
]);

export const CLI_USAGE_GROUPS = Object.freeze([
  Object.freeze({
    id: 'server-diagnostics',
    title: 'Server and Diagnostics',
    commands: Object.freeze([
      'server',
      'health',
      'status',
      'windows',
      'doctor',
      'extension-path',
      'advise',
      'mcp-config',
      'mcp-write',
      'codex-config',
      'command-catalog',
      'lighthouse-plan',
      'lighthouse-ingest',
      'last-artifact',
      'read-artifact',
      'reload-extension',
      'self-test',
      'runtime-smoke',
    ]),
  }),
  Object.freeze({
    id: 'tabs-navigation',
    title: 'Tabs and Navigation',
    commands: Object.freeze([
      'group',
      'tabs',
      'workspace',
      'set-workspace',
      'clear-workspace',
      'ensure-tab',
      'adopt-tab',
      'open',
      'with-temp-tab',
      'cleanup-run-tabs',
      'activate',
      'close-tab',
      'close-group',
      'back',
      'forward',
      'reload',
    ]),
  }),
  Object.freeze({
    id: 'page-reads',
    title: 'Page Reads',
    commands: Object.freeze([
      'wait',
      'observe',
      'act-preview',
      'act-apply',
      'find-elements',
      'extract',
      'snapshot',
      'text',
      'html',
      'grep-page',
      'page-search',
      'links',
      'tables',
      'download-discovery',
      'screenshot',
      'pdf',
      'scroll',
    ]),
  }),
  Object.freeze({
    id: 'interactions',
    title: 'Interactions',
    commands: Object.freeze([
      'click',
      'download',
      'click-at',
      'hover',
      'drag-drop',
      'type',
      'press',
      'select',
      'select-options',
      'fill-form',
      'handle-dialog',
      'upload-file',
    ]),
  }),
  Object.freeze({
    id: 'trace',
    title: 'Trace',
    commands: Object.freeze([
      'trace-start',
      'trace-summary',
      'trace-events',
      'diagnostics',
      'set-viewport',
      'emulate-network',
      'clear-emulation',
      'network-export',
      'trace-stop',
    ]),
  }),
  Object.freeze({
    id: 'browser-data',
    title: 'Browser Data',
    commands: Object.freeze([
      'history',
      'bookmarks',
      'cookies',
      'storage',
      'request',
    ]),
  }),
  Object.freeze({
    id: 'human-in-the-loop',
    title: 'Human-in-the-Loop',
    commands: Object.freeze([
      'ask',
      'session-summary',
      'recording-summary',
      'debug-bundle',
    ]),
  }),
]);

export function cliUsageLineForCommand(command) {
  const line = CLI_USAGE_LINES.find((candidate) => candidate === `chrome-bridge ${command}` || candidate.startsWith(`chrome-bridge ${command} `));
  if (!line) throw new Error(`Missing CLI usage line for command: ${command}`);
  return line;
}

export function generatedCliUsageBegin(groupId) {
  return `<!-- BEGIN GENERATED CLI USAGE: ${groupId} -->`;
}

export function generatedCliUsageEnd(groupId) {
  return `<!-- END GENERATED CLI USAGE: ${groupId} -->`;
}

export function cliUsageGroupMarkdown(groupId) {
  const group = CLI_USAGE_GROUPS.find((entry) => entry.id === groupId);
  if (!group) throw new Error(`Unknown CLI usage group: ${groupId}`);
  return [
    '```bash',
    ...group.commands.map((command) => cliUsageLineForCommand(command)),
    '```',
  ].join('\n');
}

export function generatedCliUsageBlock(groupId) {
  return [
    generatedCliUsageBegin(groupId),
    cliUsageGroupMarkdown(groupId),
    generatedCliUsageEnd(groupId),
  ].join('\n');
}
