import {
  COMMAND_PAYLOAD_SCHEMAS,
  EXTENSION_ACTIONS,
  commandDefaultTimeoutMs,
  commandRiskTier,
} from './actions.mjs';
const ACTION_DOCS = Object.freeze({
  windows: {
    category: 'scope',
    summary: 'List Chrome windows, scoped to the configured bridge group by default; includeAll requires confirmation.',
    cli: ['windows'],
    mcp: ['chrome_bridge_windows'],
    requiresConditionalConfirmation: true,
  },
  tabs: {
    category: 'scope',
    summary: 'List Chrome tabs, scoped to the configured bridge group by default; includeAll requires confirmation.',
    cli: ['tabs'],
    mcp: ['chrome_bridge_tabs'],
    requiresConditionalConfirmation: true,
  },
  group: {
    category: 'scope',
    summary: 'Show the current scoped Chrome tab group and its tabs.',
    cli: ['group'],
    mcp: ['chrome_bridge_group'],
  },
  workspace: {
    category: 'scope',
    summary: 'Show local workspace defaults, policy mode, and scoped group counts.',
    cli: ['workspace'],
    mcp: ['chrome_bridge_workspace'],
  },
  setWorkspace: {
    category: 'scope',
    summary: 'Set local workspace group title, color, and scoped/strict policy defaults.',
    cli: ['set-workspace'],
    mcp: ['chrome_bridge_set_workspace'],
    requiresConfirmation: true,
  },
  clearWorkspace: {
    category: 'scope',
    summary: 'Clear local workspace defaults and return to the default group policy.',
    cli: ['clear-workspace'],
    mcp: ['chrome_bridge_clear_workspace'],
    requiresConfirmation: true,
  },
  ensureTab: {
    category: 'navigation',
    summary: 'Create or recover the dedicated scoped Chrome work tab.',
    cli: ['ensure-tab'],
    mcp: ['chrome_bridge_ensure_tab'],
  },
  adoptTab: {
    category: 'navigation',
    summary: 'Adopt an already-open Chrome tab into the scoped bridge group.',
    cli: ['adopt-tab'],
    mcp: ['chrome_bridge_adopt_tab'],
    requiresConfirmation: true,
  },
  open: {
    category: 'navigation',
    summary: 'Open a URL in the scoped bridge tab or a new grouped tab.',
    cli: ['open'],
    mcp: ['chrome_bridge_open'],
  },
  activateTab: {
    category: 'navigation',
    summary: 'Activate a scoped tab and optionally focus its window.',
    cli: ['activate'],
    mcp: ['chrome_bridge_activate_tab'],
  },
  closeTab: {
    category: 'navigation',
    summary: 'Close one scoped tab.',
    cli: ['close-tab'],
    mcp: ['chrome_bridge_close_tab'],
    requiresConfirmation: true,
  },
  closeGroup: {
    category: 'navigation',
    summary: 'Close all tabs in the scoped bridge group.',
    cli: ['close-group'],
    mcp: ['chrome_bridge_close_group'],
    requiresConfirmation: true,
  },
  goBack: {
    category: 'navigation',
    summary: 'Navigate the selected tab backward.',
    cli: ['back'],
    mcp: ['chrome_bridge_back'],
  },
  goForward: {
    category: 'navigation',
    summary: 'Navigate the selected tab forward.',
    cli: ['forward'],
    mcp: ['chrome_bridge_forward'],
  },
  reloadTab: {
    category: 'navigation',
    summary: 'Reload the selected tab.',
    cli: ['reload'],
    mcp: ['chrome_bridge_reload_tab'],
  },
  waitForSelector: {
    category: 'read',
    summary: 'Wait for a selector to appear in the selected tab.',
    cli: ['wait'],
    mcp: ['chrome_bridge_wait_for_selector'],
  },
  observe: {
    category: 'read',
    summary: 'Read ranked actionable elements with querySelector-verified selectors without mutating page state.',
    cli: ['observe'],
    mcp: ['chrome_bridge_observe'],
  },
  findElements: {
    category: 'read',
    summary: 'Filter ranked actionable elements with querySelector-verified selectors by role, text, nearby text, href, action, or risk.',
    cli: ['find-elements'],
    mcp: ['chrome_bridge_find_elements'],
  },
  extractPage: {
    category: 'read',
    summary: 'Extract structured tables, form structure, lists, key-value blocks, or artifact-backed CPA offer presets without current form values.',
    cli: ['extract'],
    mcp: ['chrome_bridge_extract'],
  },
  snapshot: {
    category: 'read',
    summary: 'Read a bounded structured page snapshot with optional full-page rendered text coverage.',
    cli: ['snapshot'],
    mcp: ['chrome_bridge_snapshot'],
  },
  text: {
    category: 'read',
    summary: 'Read bounded visible page text with optional full-page scroll-walk coverage.',
    cli: ['text'],
    mcp: ['chrome_bridge_text'],
  },
  html: {
    category: 'read',
    summary: 'Read bounded page HTML for a selector or the whole document.',
    cli: ['html'],
    mcp: ['chrome_bridge_html'],
  },
  screenshot: {
    category: 'artifact',
    summary: 'Capture a PNG screenshot of the selected tab, full page, or selector.',
    cli: ['screenshot'],
    mcp: ['chrome_bridge_screenshot'],
  },
  printPdf: {
    category: 'artifact',
    summary: 'Print the selected tab to a local PDF artifact.',
    cli: ['pdf'],
    mcp: ['chrome_bridge_pdf'],
  },
  listSelectOptions: {
    category: 'read',
    summary: 'Read available select options without returning current selection state.',
    cli: ['select-options'],
    mcp: ['chrome_bridge_select_options'],
  },
  scroll: {
    category: 'interaction',
    summary: 'Scroll the selected tab.',
    cli: ['scroll'],
    mcp: ['chrome_bridge_scroll'],
  },
  setViewport: {
    category: 'debug',
    summary: 'Apply confirmed viewport emulation to the selected tab until clear-emulation resets it.',
    cli: ['set-viewport'],
    mcp: ['chrome_bridge_set_viewport'],
    requiresConfirmation: true,
  },
  emulateNetwork: {
    category: 'debug',
    summary: 'Apply confirmed bounded network emulation to the selected tab until clear-emulation resets it.',
    cli: ['emulate-network'],
    mcp: ['chrome_bridge_emulate_network'],
    requiresConfirmation: true,
  },
  clearEmulation: {
    category: 'debug',
    summary: 'Reset confirmed viewport and network emulation overrides for the selected tab.',
    cli: ['clear-emulation'],
    mcp: ['chrome_bridge_clear_emulation'],
    requiresConfirmation: true,
  },
  click: {
    category: 'interaction',
    summary: 'Click a selector in the selected tab.',
    cli: ['click'],
    mcp: ['chrome_bridge_click'],
    requiresConfirmation: true,
  },
  download: {
    category: 'interaction',
    summary: 'Click one confirmed selector, wait for exactly one browser download, and return local file metadata without file contents.',
    cli: ['download'],
    mcp: ['chrome_bridge_download'],
    requiresConfirmation: true,
  },
  clickAt: {
    category: 'interaction',
    summary: 'Click viewport coordinates, optionally through trusted debugger input.',
    cli: ['click-at'],
    mcp: ['chrome_bridge_click_at'],
    requiresConfirmation: true,
  },
  hover: {
    category: 'interaction',
    summary: 'Hover an element or coordinates in the selected tab.',
    cli: ['hover'],
    mcp: ['chrome_bridge_hover'],
  },
  dragDrop: {
    category: 'interaction',
    summary: 'Drag one element or coordinate point to another target in the selected tab.',
    cli: ['drag-drop'],
    mcp: ['chrome_bridge_drag_drop'],
    requiresConfirmation: true,
  },
  type: {
    category: 'interaction',
    summary: 'Type text into a selector, optionally through trusted debugger input.',
    cli: ['type'],
    mcp: ['chrome_bridge_type'],
    requiresConfirmation: true,
  },
  press: {
    category: 'interaction',
    summary: 'Press a keyboard key, optionally through trusted debugger input.',
    cli: ['press'],
    mcp: ['chrome_bridge_press'],
    requiresConfirmation: true,
  },
  select: {
    category: 'interaction',
    summary: 'Select an option in a select element.',
    cli: ['select'],
    mcp: ['chrome_bridge_select'],
    requiresConfirmation: true,
  },
  fillForm: {
    category: 'interaction',
    summary: 'Preview or apply field values without submitting or returning raw field values.',
    cli: ['fill-form'],
    mcp: ['chrome_bridge_fill_form'],
    requiresConfirmation: true,
  },
  handleDialog: {
    category: 'interaction',
    summary: 'Accept or dismiss the currently open JavaScript dialog.',
    cli: ['handle-dialog'],
    mcp: ['chrome_bridge_handle_dialog'],
    requiresConfirmation: true,
  },
  uploadFile: {
    category: 'interaction',
    summary: 'Set local files on a file input through Chrome Debugger.',
    cli: ['upload-file'],
    mcp: ['chrome_bridge_upload_file'],
    requiresConfirmation: true,
  },
  traceStart: {
    category: 'debug',
    summary: 'Start bounded console and network metadata tracing.',
    cli: ['trace-start'],
    mcp: ['chrome_bridge_trace_start'],
    requiresConfirmation: true,
  },
  traceSummary: {
    category: 'debug',
    summary: 'Read trace session metadata without returning the trace event log.',
    cli: ['trace-summary'],
    mcp: ['chrome_bridge_trace_summary'],
  },
  traceEvents: {
    category: 'debug',
    summary: 'Read recent bounded trace events.',
    cli: ['trace-events'],
    mcp: ['chrome_bridge_trace_events'],
  },
  diagnostics: {
    category: 'debug',
    summary: 'Read bounded page, trace, network-count, resource, and performance diagnostics without raw event logs.',
    cli: ['diagnostics'],
    mcp: ['chrome_bridge_diagnostics'],
  },
  traceStop: {
    category: 'debug',
    summary: 'Stop tracing and return recent events.',
    cli: ['trace-stop'],
    mcp: ['chrome_bridge_trace_stop'],
  },
  historySearch: {
    category: 'private-read',
    summary: 'Search Chrome history with explicit confirmation.',
    cli: ['history'],
    mcp: ['chrome_bridge_history_search'],
    requiresConfirmation: true,
  },
  bookmarksSearch: {
    category: 'private-read',
    summary: 'Search Chrome bookmarks with explicit confirmation.',
    cli: ['bookmarks'],
    mcp: ['chrome_bridge_bookmarks_search'],
    requiresConfirmation: true,
  },
  cookiesList: {
    category: 'private-read',
    summary: 'List Chrome cookie metadata; values require sensitive confirmation.',
    cli: ['cookies'],
    mcp: ['chrome_bridge_cookies_list'],
    requiresConfirmation: true,
    requiresSensitiveConfirmation: true,
  },
  storageSnapshot: {
    category: 'private-read',
    summary: 'Read page storage keys; values require sensitive confirmation.',
    cli: ['storage'],
    mcp: ['chrome_bridge_storage_snapshot'],
    requiresConfirmation: true,
    requiresSensitiveConfirmation: true,
  },
  fetchUrl: {
    category: 'private-read',
    summary: 'Run a bounded extension-context request; credentials require sensitive confirmation.',
    cli: ['request'],
    mcp: ['chrome_bridge_request'],
    requiresConfirmation: true,
    requiresSensitiveConfirmation: true,
  },
  askUser: {
    category: 'human',
    summary: 'Open a local prompt tab and wait for a user answer.',
    cli: ['ask'],
    mcp: ['chrome_bridge_ask_user'],
  },
  reloadExtension: {
    category: 'system',
    summary: 'Ask the unpacked extension to reload itself after local file edits; requires confirmation.',
    cli: ['reload-extension'],
    mcp: ['chrome_bridge_reload_extension'],
    requiresConfirmation: true,
  },
});

export const COMMAND_METADATA = Object.freeze(Object.fromEntries(
  EXTENSION_ACTIONS.map((action) => [action, Object.freeze({
    action,
    allowedKeys: COMMAND_PAYLOAD_SCHEMAS[action],
    riskTier: commandRiskTier(action),
    defaultTimeoutMs: commandDefaultTimeoutMs(action),
    category: ACTION_DOCS[action]?.category || 'uncategorized',
    summary: ACTION_DOCS[action]?.summary || '',
    cli: Object.freeze([...(ACTION_DOCS[action]?.cli || [])]),
    mcp: Object.freeze([...(ACTION_DOCS[action]?.mcp || [])]),
    requiresConfirmation: Boolean(ACTION_DOCS[action]?.requiresConfirmation),
    requiresConditionalConfirmation: Boolean(ACTION_DOCS[action]?.requiresConditionalConfirmation),
    requiresSensitiveConfirmation: Boolean(ACTION_DOCS[action]?.requiresSensitiveConfirmation),
  })]),
));

export const COMMAND_CATALOG = Object.freeze(EXTENSION_ACTIONS.map((action) => COMMAND_METADATA[action]));

const LOCAL_COMMAND_DOCS = Object.freeze({
  server: {
    category: 'service',
    riskTier: 'system',
    defaultTimeoutMs: null,
    summary: 'Start the local Chrome Bridge HTTP/WebSocket server.',
    cli: ['server'],
    mcp: [],
    usesLiveBridge: false,
  },
  health: {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 10_000,
    summary: 'Read local bridge health and extension connection status.',
    cli: ['health'],
    mcp: ['chrome_bridge_health'],
    usesLiveBridge: true,
  },
  status: {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Print cheap-first bridge status and token-budget recommendations.',
    cli: ['status'],
    mcp: [],
    usesLiveBridge: true,
  },
  'session-summary': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Summarize bridge health, workspace policy, scoped group state, and recommendations.',
    cli: ['session-summary'],
    mcp: ['chrome_bridge_session_summary'],
    usesLiveBridge: true,
  },
  'debug-bundle': {
    category: 'debug',
    riskTier: 'read',
    defaultTimeoutMs: 60_000,
    summary: 'Write a redacted local debug bundle with page artifacts and full trace events omitted unless requested.',
    cli: ['debug-bundle'],
    mcp: ['chrome_bridge_debug_bundle'],
    usesLiveBridge: true,
  },
  'recording-summary': {
    category: 'artifact',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Summarize an opt-in local action recording JSONL file and produce a human-reviewed replay-lite checklist.',
    cli: ['recording-summary'],
    mcp: ['chrome_bridge_recording_summary'],
    usesLiveBridge: false,
  },
  'with-temp-tab': {
    category: 'navigation',
    riskTier: 'interaction',
    defaultTimeoutMs: 120_000,
    summary: 'Open a run-owned temporary scoped tab, run a bounded read command, and clean up the tab automatically.',
    cli: ['with-temp-tab'],
    mcp: [],
    usesLiveBridge: true,
  },
  'cleanup-run-tabs': {
    category: 'navigation',
    riskTier: 'interaction',
    defaultTimeoutMs: 30_000,
    summary: 'Close tabs recorded as owned by a run id and remove them from local run state.',
    cli: ['cleanup-run-tabs'],
    mcp: [],
    usesLiveBridge: true,
  },
  'last-artifact': {
    category: 'artifact',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print metadata for the latest artifact recorded by metadata-first read outputs.',
    cli: ['last-artifact'],
    mcp: [],
    usesLiveBridge: false,
  },
  'read-artifact': {
    category: 'artifact',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Read a small head and grep slice from a local artifact without dumping the full file.',
    cli: ['read-artifact'],
    mcp: [],
    usesLiveBridge: false,
  },
  'grep-page': {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Read page text into an artifact and print regex-matching snippets only.',
    cli: ['grep-page'],
    mcp: [],
    usesLiveBridge: true,
  },
  'page-search': {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Search full-page text with ranked snippets while keeping raw page text in local artifacts.',
    cli: ['page-search'],
    mcp: ['chrome_bridge_page_search'],
    usesLiveBridge: true,
  },
  links: {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Read selector HTML into an artifact and print extracted links only.',
    cli: ['links'],
    mcp: [],
    usesLiveBridge: true,
  },
  tables: {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Read selector HTML into an artifact and print extracted tables only.',
    cli: ['tables'],
    mcp: [],
    usesLiveBridge: true,
  },
  'download-discovery': {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Discover download and offline-export candidates without clicking or fetching candidate URLs.',
    cli: ['download-discovery'],
    mcp: ['chrome_bridge_download_discovery'],
    usesLiveBridge: true,
  },
  'act-preview': {
    category: 'read',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Plan one likely next browser action from intent and observed page state without mutating the page.',
    cli: ['act-preview'],
    mcp: ['chrome_bridge_act_preview'],
    usesLiveBridge: true,
  },
  'act-apply': {
    category: 'interaction',
    riskTier: 'interaction',
    defaultTimeoutMs: 30_000,
    summary: 'Apply exactly one previously previewed action by id with confirmation, then return before/after evidence and a recommended next read.',
    cli: ['act-apply'],
    mcp: ['chrome_bridge_act_apply'],
    requiresConfirmation: true,
    usesLiveBridge: true,
  },
  'lighthouse-ingest': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Summarize a local Lighthouse JSON report into scores and failing audits.',
    cli: ['lighthouse-ingest'],
    mcp: ['chrome_bridge_lighthouse_ingest'],
    usesLiveBridge: false,
  },
  'lighthouse-plan': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print the exact local Lighthouse command and follow-up ingest command without running Lighthouse directly.',
    cli: ['lighthouse-plan'],
    mcp: ['chrome_bridge_lighthouse_plan'],
    usesLiveBridge: false,
  },
  'network-export': {
    category: 'debug',
    riskTier: 'read',
    defaultTimeoutMs: 30_000,
    summary: 'Write redacted local network-export artifacts from recent trace events without dumping raw network logs to stdout.',
    cli: ['network-export'],
    mcp: ['chrome_bridge_network_export'],
    usesLiveBridge: true,
  },
  'command-catalog': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print this shared command registry as JSON or Markdown.',
    cli: ['command-catalog'],
    mcp: ['chrome_bridge_command_catalog'],
    usesLiveBridge: false,
  },
  advise: {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Recommend the safest next CLI and MCP tools for a task without contacting Chrome.',
    cli: ['advise'],
    mcp: ['chrome_bridge_tool_advisor'],
    usesLiveBridge: false,
  },
  'mcp-config': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print MCP client configuration snippets for Claude Code, Cursor, Codex, VS Code, Windsurf, Hermes, or generic stdio clients.',
    cli: ['mcp-config'],
    mcp: ['chrome_bridge_mcp_config'],
    usesLiveBridge: false,
  },
  'mcp-write': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Write or merge a project-local MCP client config file, or render one to an explicit path without touching user-global config by default.',
    cli: ['mcp-write'],
    mcp: [],
    usesLiveBridge: false,
  },
  'self-test': {
    category: 'verification',
    riskTier: 'read',
    defaultTimeoutMs: 10_000,
    summary: 'Run static project parity checks without touching Chrome.',
    cli: ['self-test'],
    mcp: ['chrome_bridge_self_test'],
    usesLiveBridge: false,
  },
  'runtime-smoke': {
    category: 'verification',
    riskTier: 'interaction',
    defaultTimeoutMs: 180_000,
    summary: 'Run the real-browser fixture smoke test against the live bridge.',
    cli: ['runtime-smoke'],
    mcp: ['chrome_bridge_runtime_smoke'],
    usesLiveBridge: true,
  },
  doctor: {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 10_000,
    summary: 'Inspect local installation paths offline; pass --live-checks to probe bridge health and Chrome settings.',
    cli: ['doctor'],
    mcp: ['chrome_bridge_doctor'],
    liveBridge: 'optional',
    usesLiveBridge: false,
  },
  'extension-path': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print the unpacked extension directory path.',
    cli: ['extension-path'],
    mcp: ['chrome_bridge_extension_path'],
    usesLiveBridge: false,
  },
  'codex-config': {
    category: 'diagnostic',
    riskTier: 'read',
    defaultTimeoutMs: 5_000,
    summary: 'Print the legacy Codex MCP configuration snippet using the current Node executable.',
    cli: ['codex-config'],
    mcp: ['chrome_bridge_codex_config'],
    usesLiveBridge: false,
  },
});

export const LOCAL_COMMAND_METADATA = Object.freeze(Object.fromEntries(
  Object.entries(LOCAL_COMMAND_DOCS).map(([id, doc]) => [id, Object.freeze({
    id,
    category: doc.category,
    riskTier: doc.riskTier,
    defaultTimeoutMs: doc.defaultTimeoutMs,
    summary: doc.summary,
    cli: Object.freeze([...doc.cli]),
    mcp: Object.freeze([...doc.mcp]),
    requiresConfirmation: Boolean(doc.requiresConfirmation),
    liveBridge: doc.liveBridge || (doc.usesLiveBridge ? 'yes' : 'no'),
    usesLiveBridge: Boolean(doc.usesLiveBridge),
  })]),
));

export const LOCAL_COMMAND_CATALOG = Object.freeze(Object.values(LOCAL_COMMAND_METADATA));
